export const print = [
  {
    type: "text",
    align: "center",
    body: "Tashkent City Park",
    font: "large",
  },
  {
    type: "text",
    align: "center",
    body: "\n\r\n\r",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Pullik kirish taloni",
    font: "bold",
  },
  {
    type: "text",
    align: "center",
    body: "\n\r",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Hujjat raqami:                         P-3390864",
    font: "normal",
  },
  {
    type: "text",
    align: "left",
    body: "Kirish vaqti:                2024-12-12 13:49:01",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "Avtomobil raqami:                    aniqlanmadi",
    font: "normal",
  },
  {
    type: "text",
    align: "center",
    body: "\n\r\n\r",
    font: "normal",
  },
  {
    type: "qrCode",
    align: "center",
    body: "qr code tayorlanayabdi",
    font: "normal",
  },
];
